---
site_name: Mnemorium

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tracking

nav:
  - Home: index.md
  - Development:
      - Overview: development/Overview.md
      - API documentation:
          - Overview: development/api/Overview.md
          - Spec: development/api/Spec.md
      - Glossary: development/Glossary.md
      - Style Guide: development/StyleGuide.md
      - Test: development/Test.md
      - Use Cases: development/UseCases.md

plugins:
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml
  - search
  - neoteroi.mkdocsoad

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
