INSERT INTO language (language_id, english_name, native_name, code) VALUES
(1, 'Abkhazian', 'аҧсуа бызшәа', 'ab'),
(2, 'Afar', 'Afaraf', 'aa'),
(3, 'Afrikaans', 'Afrikaans', 'af'),
(4, 'Akan', 'Akan', 'ak'),
(5, 'Albanian', 'Shqip', 'sq'),
(6, 'Amharic', 'አማርኛ', 'am'),
(7, 'Arabic', 'العربية', 'ar'),
(8, 'Aragonese', 'aragonés', 'an'),
(9, 'Assamese', 'অসমীয়া', 'as'),
(10, 'Avaric', 'авар мацӀ', 'av'),
(11, 'Aymara', 'aymar aru', 'ay'),
(12, 'Azerbaijani', 'azərbaycan dili', 'az'),
(13, 'Bambara', 'bamanankan', 'bm'),
(14, 'Bashkir', 'башҡорт теле', 'ba'),
(15, 'Basque', 'euskara', 'eu'),
(16, 'Belarusian', 'беларуская мова', 'be'),
(17, 'Bengali', 'বাংলা', 'bn'),
(18, 'Bihari', 'भोजपुरी', 'bh'),
(19, 'Bislama', 'Bislama', 'bi'),
(20, 'Bosnian', 'bosanski jezik', 'bs'),
(21, 'Breton', 'brezhoneg', 'br'),
(22, 'Bulgarian', 'български език', 'bg'),
(23, 'Burmese', 'ဗမာစာ', 'my'),
(24, 'Catalan', 'català', 'ca'),
(25, 'Chamorro', 'Chamoru', 'ch'),
(26, 'Chechen', 'нохчийн мотт', 'ce'),
(27, 'Chichewa', 'chiCheŵa', 'ny'),
(28, 'Chinese', '中文', 'zh'),
(29, 'Church Slavic', 'ѩзыкъ словѣньскъ', 'cu'),
(30, 'Chuvash', 'чӑваш чӗлхи', 'cv'),
(31, 'Cornish', 'Kernewek', 'kw'),
(32, 'Corsican', 'corsu', 'co'),
(33, 'Cree', 'ᓀᐦᐃᔭᐍᐏᐣ', 'cr'),
(34, 'Croatian', 'hrvatski jezik', 'hr'),
(35, 'Czech', 'čeština', 'cs'),
(36, 'Danish', 'dansk', 'da'),
(37, 'Divehi', 'ދިވެހި', 'dv'),
(38, 'Dutch', 'Nederlands', 'nl'),
(39, 'Dzongkha', 'རྫོང་ཁ', 'dz'),
(40, 'English', 'English', 'en'),
(41, 'Esperanto', 'Esperanto', 'eo'),
(42, 'Estonian', 'eesti', 'et'),
(43, 'Ewe', 'Eʋegbe', 'ee'),
(44, 'Faroese', 'føroyskt', 'fo'),
(45, 'Fijian', 'vosa Vakaviti', 'fj'),
(46, 'Finnish', 'suomi', 'fi'),
(47, 'French', 'Français', 'fr'),
(48, 'Fulah', 'Fulfulde', 'ff'),
(49, 'Galician', 'Galego', 'gl'),
(50, 'Ganda', 'Luganda', 'lg'),
(51, 'Georgian', 'ქართული', 'ka'),
(52, 'German', 'Deutsch', 'de'),
(53, 'Greek', 'Ελληνικά', 'el'),
(54, 'Guarani', 'Avañeẽ', 'gn'),
(55, 'Gujarati', 'ગુજરાતી', 'gu'),
(56, 'Haitian', 'Kreyòl ayisyen', 'ht'),
(57, 'Hausa', 'هَوُسَ', 'ha'),
(58, 'Hebrew', 'עברית', 'he'),
(59, 'Herero', 'Otjiherero', 'hz'),
(60, 'Hindi', 'हिन्दी', 'hi'),
(61, 'Hiri Motu', 'Hiri Motu', 'ho'),
(62, 'Hungarian', 'magyar', 'hu'),
(63, 'Icelandic', 'Íslenska', 'is'),
(64, 'Ido', 'Ido', 'io'),
(65, 'Igbo', 'Asụsụ Igbo', 'ig'),
(66, 'Indonesian', 'Bahasa Indonesia', 'id'),
(67, 'Interlingua', 'Interlingua', 'ia'),
(68, 'Interlingue', 'Interlingue', 'ie'),
(69, 'Inuktitut', 'ᐃᓄᒃᑎᑐᑦ', 'iu'),
(70, 'Inupiaq', 'Iñupiaq', 'ik'),
(71, 'Irish', 'Gaeilge', 'ga'),
(72, 'Italian', 'Italiano', 'it'),
(73, 'Japanese', '日本語', 'ja'),
(74, 'Javanese', 'ꦧꦱꦗꦮ', 'jv'),
(75, 'Kalaallisut', 'kalaallisut', 'kl'),
(76, 'Kannada', 'ಕನ್ನಡ', 'kn'),
(77, 'Kanuri', 'Kanuri', 'kr'),
(78, 'Kashmiri', 'कश्मीरी', 'ks'),
(79, 'Kazakh', 'қазақ тілі', 'kk'),
(80, 'Khmer', 'ខ្មែរ', 'km'),
(81, 'Kikuyu', 'Gĩkũyũ', 'ki'),
(82, 'Kinyarwanda', 'Ikinyarwanda', 'rw'),
(83, 'Komi', 'коми кыв', 'kv'),
(84, 'Kongo', 'Kikongo', 'kg'),
(85, 'Korean', '한국어', 'ko'),
(86, 'Kuanyama', 'Kuanyama', 'kj'),
(87, 'Kurdish', 'Kurdî', 'ku'),
(88, 'Kyrgyz', 'Кыргызча', 'ky'),
(89, 'Lao', 'ພາສາລາວ', 'lo'),
(90, 'Latin', 'latine', 'la'),
(91, 'Latvian', 'latviešu valoda', 'lv'),
(92, 'Limburgish', 'Limburgs', 'li'),
(93, 'Lingala', 'Lingála', 'ln'),
(94, 'Lithuanian', 'lietuvių kalba', 'lt'),
(95, 'Luba-Katanga', 'Kiluba', 'lu'),
(96, 'Luxembourgish', 'Lëtzebuergesch', 'lb'),
(97, 'Macedonian', 'македонски јазик', 'mk'),
(98, 'Malagasy', 'fiteny malagasy', 'mg'),
(99, 'Malay', 'Bahasa Melayu', 'ms'),
(100, 'Malayalam', 'മലയാളം', 'ml'),
(101, 'Maltese', 'Malti', 'mt'),
(102, 'Manx', 'Gaelg', 'gv'),
(103, 'Maori', 'te reo Māori', 'mi'),
(104, 'Marathi', 'मराठी', 'mr'),
(105, 'Marshallese', 'Kajin M̧ajeļ', 'mh'),
(106, 'Mongolian', 'Монгол хэл', 'mn'),
(107, 'Nauru', 'Dorerin Naoero', 'na'),
(108, 'Navajo', 'Diné bizaad', 'nv'),
(109, 'Ndonga', 'Owambo', 'ng'),
(110, 'Nepali', 'नेपाली', 'ne'),
(111, 'North Ndebele', 'isiNdebele', 'nd'),
(112, 'Northern Sami', 'Davvisámegiella', 'se'),
(113, 'Norwegian', 'Norsk', 'no'),
(114, 'Norwegian Bokmål', 'Norsk Bokmål', 'nb'),
(115, 'Norwegian Nynorsk', 'Norsk Nynorsk', 'nn'),
(116, 'Occitan', 'occitan', 'oc'),
(117, 'Ojibwa', 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'oj'),
(118, 'Oriya', 'ଓଡ଼ିଆ', 'or'),
(119, 'Oromo', 'Afaan Oromoo', 'om'),
(120, 'Ossetian', 'ирон æвзаг', 'os'),
(121, 'Pali', 'पाऴि', 'pi'),
(122, 'Pashto', 'پښتو', 'ps'),
(123, 'Persian', 'فارسی', 'fa'),
(124, 'Polish', 'język polski', 'pl'),
(125, 'Portuguese', 'Português', 'pt'),
(126, 'Punjabi', 'ਪੰਜਾਬੀ', 'pa'),
(127, 'Quechua', 'Runa Simi', 'qu'),
(128, 'Romanian', 'Română', 'ro'),
(129, 'Romansh', 'Rumantsch Grischun', 'rm'),
(130, 'Rundi', 'Ikirundi', 'rn'),
(131, 'Russian', 'Русский', 'ru'),
(132, 'Samoan', 'gagana fa''a Samoa', 'sm'),
(133, 'Sango', 'yângâ tî sängö', 'sg'),
(134, 'Sanskrit', 'संस्कृतम्', 'sa'),
(135, 'Sardinian', 'sardu', 'sc'),
(136, 'Scottish Gaelic', 'Gàidhlig', 'gd'),
(137, 'Serbian', 'српски језик', 'sr'),
(138, 'Shona', 'chiShona', 'sn'),
(139, 'Sichuan Yi', 'ꆈꌠ꒿ Nuosuhxop', 'ii'),
(140, 'Sindhi', 'सिन्धी', 'sd'),
(141, 'Sinhala', 'සිංහල', 'si'),
(142, 'Slovak', 'Slovenčina', 'sk'),
(143, 'Slovenian', 'Slovenščina', 'sl'),
(144, 'Somali', 'Soomaaliga', 'so'),
(145, 'South Ndebele', 'siNdebele', 'nr'),
(146, 'Southern Sotho', 'Sesotho', 'st'),
(147, 'Spanish', 'Español', 'es'),
(148, 'Sundanese', 'Basa Sunda', 'su'),
(149, 'Swahili', 'Kiswahili', 'sw'),
(150, 'Swati', 'SiSwati', 'ss'),
(151, 'Swedish', 'Svenska', 'sv'),
(152, 'Tagalog', 'Wikang Tagalog', 'tl'),
(153, 'Tahitian', 'Reo Tahiti', 'ty'),
(154, 'Tajik', 'тоҷикӣ', 'tg'),
(155, 'Tamil', 'தமிழ்', 'ta'),
(156, 'Tatar', 'татар теле', 'tt'),
(157, 'Telugu', 'తెలుగు', 'te'),
(158, 'Thai', 'ไทย', 'th'),
(159, 'Tibetan', 'བོད་ཡིག', 'bo'),
(160, 'Tigrinya', 'ትግርኛ', 'ti'),
(161, 'Tonga', 'Faka Tonga', 'to'),
(162, 'Tsonga', 'Xitsonga', 'ts'),
(163, 'Tswana', 'Setswana', 'tn'),
(164, 'Turkish', 'Türkçe', 'tr'),
(165, 'Turkmen', 'Türkmen', 'tk'),
(166, 'Twi', 'Twi', 'tw'),
(167, 'Uighur', 'ئۇيغۇرچە', 'ug'),
(168, 'Ukrainian', 'Українська', 'uk'),
(169, 'Urdu', 'اردو', 'ur'),
(170, 'Uzbek', 'Oʻzbek', 'uz'),
(171, 'Venda', 'Tshivenḓa', 've'),
(172, 'Vietnamese', 'Tiếng Việt', 'vi'),
(173, 'Volapük', 'Volapük', 'vo'),
(174, 'Walloon', 'Walon', 'wa'),
(175, 'Welsh', 'Cymraeg', 'cy'),
(176, 'Western Frisian', 'Frysk', 'fy'),
(177, 'Wolof', 'Wollof', 'wo'),
(178, 'Xhosa', 'isiXhosa', 'xh'),
(179, 'Yiddish', 'ייִדיש', 'yi'),
(180, 'Yoruba', 'Yorùbá', 'yo'),
(181, 'Zhuang', 'Saɯ cueŋƅ', 'za'),
(182, 'Zulu', 'isiZulu', 'zu');
