use std::future::Future;

use crate::domain::alias::NumericID;
use crate::domain::port::error::StorageError;

/// Opaque identifier of an upload session.
///
/// The identifier is generated by the caller of the port and carried opaquely
/// by the adapter.
#[derive(Debug, Clone, PartialEq, Eq)]
#[non_exhaustive]
pub struct UploadId(String);

impl UploadId {
    /// Initialise an upload identifier from its opaque value.
    #[must_use]
    pub fn new(value: String) -> Self {
        Self(value)
    }

    /// Return the opaque value of the identifier.
    #[must_use]
    pub fn value(&self) -> &str {
        &self.0
    }
}

/// Port for storing uploaded file content on a storage backend.
///
/// The port covers the chunked upload flow: begin a session for a file, then
/// append chunks to it. Upload session state is owned by the adapter and only
/// reachable through the [`UploadId`].
#[cfg_attr(test, mockall::automock)]
pub trait FileStorage: Send + Sync {
    /// Append the raw bytes of one chunk to the upload identified by `id`.
    fn append_chunk(
        &self,
        id: &UploadId,
        chunk: Vec<u8>,
    ) -> impl Future<Output = Result<(), StorageError>> + Send;

    /// Begin an upload for the file named `file_name` owned by `user_id` with
    /// media type `mime_type_id`.
    ///
    /// Creates the staging file of the upload identified by `id`. Returns an
    /// error when a staging file for `id` already exists.
    fn begin(
        &self,
        id: &UploadId,
        file_name: &str,
        user_id: NumericID,
        mime_type_id: &str,
    ) -> impl Future<Output = Result<(), StorageError>> + Send;
}
