#!/usr/bin/env python3
"""Validate and apply the ci-triage proposals document.

The unattended triage agent holds a read-only token and prints a proposed-writes
document; this script is the only writer. It rejects every write that targets an
issue outside the open set read at apply time, uses an operation or label outside
the `triage` skill's vocabulary, violates the skill's label invariants or cap, or
does not open its body with the AI disclosure. An instruction injected into issue
text therefore cannot cause a write the skill does not define.

`LABELS` restates the `triage` skill's vocabulary
(`.opencode/skills/triage/SKILL.md`, "Label vocabulary"); `test/unit` asserts the
two stay equal.

Usage:
  script/apply_triage_writes.py --repo OWNER/REPO --proposals PATH [--dry-run]

The token is read from `GH_TOKEN`. See docs/development/TechnicalDesign.md § 5
(CI and prompt assets), `TEST-051`, and § 6, `DEPS-002`.
"""

import argparse
import json
import os
import sys
from pathlib import Path
from typing import Any

import requests

API = "https://api.github.com"
DISCLOSURE = "> _This issue was generated by AI._"
CATEGORY_LABELS = frozenset({"bug", "enhancement", "documentation"})
STATE_LABELS = frozenset(
    {
        "needs-triage",
        "needs-info",
        "needs-developer",
        "ready-for-agent",
        "ready-for-human",
        "obsolete",
        "duplicate",
    }
)
LABELS = CATEGORY_LABELS | STATE_LABELS
OPS = frozenset({"set_labels", "comment", "append_body", "close", "create_issue"})
CAP = 25


class ValidationError(Exception):
    """The proposals violate the structural bound."""


def check_body(value: Any, where: str) -> str:
    if not isinstance(value, str) or not value.startswith(DISCLOSURE):
        raise ValidationError(f"{where}: body must open with the AI disclosure")
    return value


def check_labels(value: Any, where: str, *, allow_empty: bool = False) -> None:
    if not isinstance(value, list) or not all(label in LABELS for label in value):
        raise ValidationError(f"{where}: labels must be a subset of {sorted(LABELS)}")
    if not value and not allow_empty:
        raise ValidationError(f"{where}: at least one label is required")
    if len([label for label in value if label in CATEGORY_LABELS]) > 1:
        raise ValidationError(f"{where}: at most one category label")
    if len([label for label in value if label in STATE_LABELS]) > 1:
        raise ValidationError(f"{where}: at most one state label")


def check_number(value: Any, open_issues: dict[int, int], where: str) -> int:
    if not isinstance(value, int) or value not in open_issues:
        raise ValidationError(f"{where}: {value!r} is not an open issue")
    return value


def parse_document(text: str) -> dict[str, Any]:
    start, end = text.find("{"), text.rfind("}")
    if start == -1 or end <= start:
        raise ValidationError("no JSON object in the agent output")
    try:
        document = json.loads(text[start : end + 1])
    except json.JSONDecodeError as error:
        raise ValidationError(f"invalid proposals JSON: {error}") from error
    if not isinstance(document, dict) or not isinstance(document.get("writes"), list):
        raise ValidationError("proposals must be an object with a `writes` list")
    return document


def validate(document: dict[str, Any], open_issues: dict[int, int]) -> None:
    comments: dict[int, str] = {}
    touched: set[int] = set()
    created = 0
    for write in document["writes"]:
        if not isinstance(write, dict):
            raise ValidationError("every write must be an object")
        op = write.get("op")
        if op not in OPS:
            raise ValidationError(f"unknown op {op!r}")
        if op == "create_issue":
            if not isinstance(write.get("title"), str) or not write["title"].strip():
                raise ValidationError("create_issue: title is required")
            check_body(write.get("body"), "create_issue")
            check_labels(write.get("labels", []), "create_issue", allow_empty=True)
            sub_issues = write.get("sub_issues")
            if not isinstance(sub_issues, list) or not sub_issues:
                raise ValidationError("create_issue: at least one sub_issue is required")
            for number in sub_issues:
                check_number(number, open_issues, "create_issue sub_issue")
                touched.add(number)
            created += 1
            continue
        issue = check_number(write.get("issue"), open_issues, f"{op} issue")
        if op == "set_labels":
            check_labels(write.get("labels"), "set_labels")
        elif op == "comment":
            comments[issue] = f"{comments.get(issue, '')}\n{check_body(write.get('body'), 'comment')}"
        elif op == "append_body":
            check_body(write.get("body"), "append_body")
        elif op == "close":
            if write.get("reason") != "duplicate":
                raise ValidationError("close: reason must be duplicate")
            duplicate_of = check_number(write.get("duplicate_of"), open_issues, "close duplicate_of")
            if duplicate_of >= issue:
                raise ValidationError("close: duplicate_of must be the older issue")
            if f"#{duplicate_of}" not in comments.get(issue, ""):
                raise ValidationError("close: a linking comment naming the duplicate must precede the close")
        touched.add(issue)
    if len(touched) + created > CAP:
        raise ValidationError(f"more than {CAP} issues touched in one sweep")


class Client:
    def __init__(self, repo: str, token: str) -> None:
        self.repo = repo
        self.session = requests.Session()
        self.session.headers.update(
            {
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            }
        )

    def open_issues(self) -> dict[int, int]:
        issues: dict[int, int] = {}
        url: str | None = f"{API}/repos/{self.repo}/issues"
        params: dict[str, Any] | None = {"state": "open", "per_page": 100}
        while url:
            response = self.session.get(url, params=params, timeout=30)
            response.raise_for_status()
            for issue in response.json():
                if "pull_request" not in issue:
                    issues[issue["number"]] = issue["id"]
            url = response.links.get("next", {}).get("url")
            params = None
        return issues

    def apply(self, write: dict[str, Any], open_issues: dict[int, int]) -> None:
        op = write["op"]
        if op == "set_labels":
            self.session.put(
                f"{API}/repos/{self.repo}/issues/{write['issue']}/labels",
                json={"labels": write["labels"]},
                timeout=30,
            ).raise_for_status()
        elif op == "comment":
            self.session.post(
                f"{API}/repos/{self.repo}/issues/{write['issue']}/comments",
                json={"body": write["body"]},
                timeout=30,
            ).raise_for_status()
        elif op == "append_body":
            current = self.session.get(f"{API}/repos/{self.repo}/issues/{write['issue']}", timeout=30)
            current.raise_for_status()
            body = current.json().get("body") or ""
            appended = f"{body}\n\n{write['body']}" if body else write["body"]
            self.session.patch(
                f"{API}/repos/{self.repo}/issues/{write['issue']}",
                json={"body": appended},
                timeout=30,
            ).raise_for_status()
        elif op == "close":
            self.session.patch(
                f"{API}/repos/{self.repo}/issues/{write['issue']}",
                json={"state": "closed", "state_reason": "duplicate"},
                timeout=30,
            ).raise_for_status()
        elif op == "create_issue":
            created = self.session.post(
                f"{API}/repos/{self.repo}/issues",
                json={
                    "title": write["title"],
                    "body": write["body"],
                    "labels": write.get("labels", []),
                },
                timeout=30,
            )
            created.raise_for_status()
            number = created.json()["number"]
            for sub_issue in write["sub_issues"]:
                self.session.post(
                    f"{API}/repos/{self.repo}/issues/{number}/sub_issues",
                    json={"sub_issue_id": open_issues[sub_issue]},
                    timeout=30,
                ).raise_for_status()


def main() -> int:
    parser = argparse.ArgumentParser(description="Apply the ci-triage proposals document.")
    parser.add_argument("--repo", required=True, help="OWNER/REPO")
    parser.add_argument("--proposals", required=True, help="path to the agent output")
    parser.add_argument("--dry-run", action="store_true", help="validate only; write nothing")
    args = parser.parse_args()

    token = os.environ.get("GH_TOKEN", "")
    if not token:
        print("GH_TOKEN is not set", file=sys.stderr)
        return 1
    try:
        document = parse_document(Path(args.proposals).read_text(encoding="utf-8"))
    except (OSError, ValidationError) as error:
        print(f"proposals rejected: {error}", file=sys.stderr)
        return 1

    client = Client(args.repo, token)
    open_issues = client.open_issues()
    try:
        validate(document, open_issues)
    except ValidationError as error:
        print(f"proposals rejected: {error}", file=sys.stderr)
        return 1

    if args.dry_run:
        print(f"dry run: {len(document['writes'])} proposed writes validated; none applied")
        return 0

    failures = 0
    for write in document["writes"]:
        target = write.get("issue", write.get("title"))
        try:
            client.apply(write, open_issues)
            print(f"applied {write['op']} to {target}")
        except requests.RequestException as error:
            failures += 1
            print(f"write failed ({write['op']} {target}): {error}", file=sys.stderr)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
