#!/bin/bash
set -u -o pipefail

# Validate the commit/PR scope taxonomy defined by GOV-001.
#
# Canonical source: docs/development/TechnicalDesign.md, "Repository Governance"
# -> "1. Scope". The table there names the closed scope set and the paths each
# scope owns. This script:
#   1. parses that table;
#   2. asserts the set matches the `scopes:` list in .github/workflows/ci.yml;
#   3. asserts every tracked path maps to exactly one scope (longest prefix);
#   4. asserts no scope owns zero paths.
#
# See docs/development/TechnicalDesign.md § 7 (Repository Governance), GOV-001.

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
readonly SCRIPT_DIR
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
readonly REPO_ROOT
readonly TECH_DESIGN="docs/development/TechnicalDesign.md"
readonly CI_WORKFLOW=".github/workflows/ci.yml"

# Paths exempt from the mapping: generated by the release tooling, never scoped.
readonly EXEMPT_PATHS=(
	"CHANGELOG.md"
)

usage() {
	echo "Usage: script/check_scopes.sh"
	echo ""
	echo "  Validate the commit/PR scope taxonomy (GOV-001) declared in"
	echo "  $TECH_DESIGN against the repository's tracked paths and the CI"
	echo "  scope allow-list. Exits non-zero on any inconsistency."
}

die() {
	printf 'error: %s\n' "$*" >&2
	exit 1
}

# Print "scope<TAB>glob" for every row of the scope table.
scope_rows() {
	awk '
		/^### 1\. Scope$/ { in_section = 1; next }
		in_section && /^### / { in_section = 0 }
		in_section && /^\|/ {
			rows++
			if (rows <= 2) next
			split($0, cell, "|")
			scope = cell[3]
			path = cell[4]
			gsub(/^[[:space:]]+|[[:space:]]+$/, "", scope)
			gsub(/^[[:space:]]+|[[:space:]]+$/, "", path)
			gsub(/`/, "", scope)
			gsub(/`/, "", path)
			if (scope != "" && path != "") printf "%s\t%s\n", scope, path
		}
	' "$TECH_DESIGN"
}

# Print the scope names declared in the CI workflow's `scopes:` block.
ci_scopes() {
	awk '
		/^[[:space:]]*scopes: \|$/ { in_list = 1; next }
		in_list {
			if ($0 ~ /^[[:space:]]+[A-Za-z0-9_-]+[[:space:]]*$/) {
				line = $0
				gsub(/^[[:space:]]+|[[:space:]]+$/, "", line)
				print line
			} else {
				in_list = 0
			}
		}
	' "$CI_WORKFLOW"
}

main() {
	case "${1:-}" in
	-h | --help | help)
		usage
		return 0
		;;
	--) ;;
	"") ;;
	*) die "unexpected argument: $1" ;;
	esac

	cd -- "$REPO_ROOT" || die "cannot enter $REPO_ROOT"
	[ -f "$TECH_DESIGN" ] || die "missing $TECH_DESIGN"
	[ -f "$CI_WORKFLOW" ] || die "missing $CI_WORKFLOW"

	local -a scopes=() globs=()
	while IFS=$'\t' read -r scope glob; do
		scopes+=("$scope")
		globs+=("$glob")
	done < <(scope_rows)

	[ "${#globs[@]}" -gt 0 ] || die "no scope rows parsed from $TECH_DESIGN"

	local -a table_set=() ci_set=()
	mapfile -t table_set < <(printf '%s\n' "${scopes[@]}" | sort -u)
	mapfile -t ci_set < <(ci_scopes | sort -u)

	local diff_output
	if ! diff_output="$(diff -u <(printf '%s\n' "${ci_set[@]}") <(printf '%s\n' "${table_set[@]}"))"; then
		printf '%s\n' "$diff_output" >&2
		die "the scope table in $TECH_DESIGN and the 'scopes:' list in $CI_WORKFLOW differ (GOV-001)"
	fi

	local -A owner_count=()
	local file best best_len i matches skip
	local exit_status=0

	while IFS= read -r file; do
		skip=0
		for exempt in "${EXEMPT_PATHS[@]}"; do
			if [ "$file" = "$exempt" ]; then
				skip=1
				break
			fi
		done
		[ "$skip" -eq 1 ] && continue

		best=""
		best_len=0
		matches=0
		for i in "${!globs[@]}"; do
			# The glob on the right is intentional: match as a pattern.
			# shellcheck disable=SC2053
			if [[ $file == ${globs[$i]} ]]; then
				if [ "${#globs[$i]}" -gt "$best_len" ]; then
					best="${scopes[$i]}"
					best_len="${#globs[$i]}"
					matches=1
				elif [ "${#globs[$i]}" -eq "$best_len" ] && [ "${scopes[$i]}" != "$best" ]; then
					matches=$((matches + 1))
				fi
			fi
		done

		if [ "$matches" -gt 1 ]; then
			printf 'error: %s matches more than one scope at the same prefix length\n' "$file" >&2
			exit_status=1
			continue
		fi
		if [ -z "$best" ]; then
			printf 'error: %s is owned by no scope in %s\n' "$file" "$TECH_DESIGN" >&2
			exit_status=1
			continue
		fi
		owner_count["$best"]=$((${owner_count["$best"]:-0} + 1))
	done < <(git ls-files)

	local scope_name
	for scope_name in "${table_set[@]}"; do
		if [ "${owner_count["$scope_name"]:-0}" -eq 0 ]; then
			printf 'error: scope "%s" owns no tracked path\n' "$scope_name" >&2
			exit_status=1
		fi
	done

	if [ "$exit_status" -ne 0 ]; then
		die "scope taxonomy is inconsistent (GOV-001)"
	fi

	printf 'Scope taxonomy OK: %d scopes, %d tracked paths mapped.\n' \
		"${#table_set[@]}" "$(git ls-files | wc -l | tr -d ' ')"
}

main "$@"
