"""Unit tests for the triage static guards and the proposals writer.

These drive the pure decision functions in `script/` from fixtures, one case per
rejection branch. The credentialed HTTP path in `apply_triage_writes.py` is not
exercised (no live GitHub); see `docs/development/TechnicalDesign.md` § 5,
`TEST-051`.
"""

import importlib.util
import json
import re
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
SKILL = ROOT / ".opencode" / "skills" / "triage" / "SKILL.md"
DISCLOSURE = "> _This issue was generated by AI._"
OPEN_ISSUES = {41: 1041, 42: 1042, 43: 1043, 44: 1044}


def load(name: str, filename: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "script" / filename)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


frontmatter = load("check_ci_triage_frontmatter", "check_ci_triage_frontmatter.py")
config_guard = load("check_opencode_config", "check_opencode_config.py")
applier = load("apply_triage_writes", "apply_triage_writes.py")


# --- frontmatter guard -------------------------------------------------------

GOOD_PERMISSIONS = """\
  - { action: read, resource: "*", effect: allow }
  - { action: read, resource: "*.env*", effect: deny }
  - { action: glob, resource: "*", effect: allow }
  - { action: grep, resource: "*", effect: allow }
  - { action: grep, resource: "*.env*", effect: deny }
  - { action: skill, resource: "*", effect: allow }
  - { action: shell, resource: "*", effect: deny }
  - { action: webfetch, resource: "*", effect: deny }
  - { action: websearch, resource: "*", effect: deny }
  - { action: external_directory, resource: "*", effect: deny }
  - { action: edit, resource: "*", effect: deny }
  - { action: subagent, resource: "*", effect: deny }
  - { action: question, resource: "*", effect: deny }
"""


def write_agent(tmp_path: Path, permissions_yaml: str) -> Path:
    path = tmp_path / "ci-triage.md"
    path.write_text(
        f"---\nmode: primary\npermissions:\n{permissions_yaml}---\n\n# Role\n",
        encoding="utf-8",
    )
    return path


def run_frontmatter(monkeypatch, tmp_path, permissions_yaml) -> None:
    monkeypatch.setattr(frontmatter, "AGENT", write_agent(tmp_path, permissions_yaml))
    frontmatter.main()


def test_frontmatter_accepts_the_configured_deny_list(monkeypatch, tmp_path):
    run_frontmatter(monkeypatch, tmp_path, GOOD_PERMISSIONS)


def test_frontmatter_rejects_missing_deny(monkeypatch, tmp_path):
    with pytest.raises(SystemExit):
        run_frontmatter(
            monkeypatch,
            tmp_path,
            GOOD_PERMISSIONS.replace('  - { action: shell, resource: "*", effect: deny }\n', ""),
        )


def test_frontmatter_rejects_a_deny_neutralized_by_a_later_allow(monkeypatch, tmp_path):
    with pytest.raises(SystemExit):
        run_frontmatter(
            monkeypatch,
            tmp_path,
            GOOD_PERMISSIONS + '  - { action: shell, resource: "*", effect: allow }\n',
        )


def test_frontmatter_rejects_a_changed_external_directory_sequence(monkeypatch, tmp_path):
    reordered = GOOD_PERMISSIONS.replace(
        '  - { action: external_directory, resource: "*", effect: deny }\n',
        "",
    )
    with pytest.raises(SystemExit):
        run_frontmatter(monkeypatch, tmp_path, reordered)


# --- config guard ------------------------------------------------------------

VALID_CONFIG = {
    "$schema": "https://opencode.ai/config.json",
    "mcp": {
        "servers": {
            "github": {
                "type": "remote",
                "url": "https://api.githubcopilot.com/mcp/",
                "oauth": False,
                "headers": {"Authorization": "Bearer {env:GITHUB_MCP_TOKEN}"},
            }
        }
    },
}


def run_config_guard(monkeypatch, tmp_path, config) -> None:
    path = tmp_path / "config.json"
    path.write_text(json.dumps(config), encoding="utf-8")
    monkeypatch.setattr(config_guard, "CONFIG", path)
    config_guard.main()


def test_config_guard_accepts_the_v2_shape(monkeypatch, tmp_path):
    run_config_guard(monkeypatch, tmp_path, VALID_CONFIG)


def test_config_guard_rejects_the_v1_shape(monkeypatch, tmp_path):
    v1 = {"$schema": VALID_CONFIG["$schema"], "mcp": {"github": VALID_CONFIG["mcp"]["servers"]["github"]}}
    with pytest.raises(SystemExit):
        run_config_guard(monkeypatch, tmp_path, v1)


@pytest.mark.parametrize(
    "mutate",
    [
        lambda config: config.update({"permissions": {}}),
        lambda config: config["mcp"].update({"other": {}}),
        lambda config: config["mcp"]["servers"].update({"other": {}}),
        lambda config: config["mcp"]["servers"]["github"].update({"disabled": True}),
        lambda config: config["mcp"]["servers"]["github"].update({"url": "https://example.test/"}),
        lambda config: config["mcp"]["servers"]["github"].update({"oauth": True}),
        lambda config: config["mcp"]["servers"]["github"].update({"headers": {}}),
    ],
)
def test_config_guard_rejects_bad_configs(monkeypatch, tmp_path, mutate):
    config = json.loads(json.dumps(VALID_CONFIG))
    mutate(config)
    with pytest.raises(SystemExit):
        run_config_guard(monkeypatch, tmp_path, config)


# --- proposals writer --------------------------------------------------------


def write(**kwargs):
    return kwargs


def valid_document():
    return {
        "writes": [
            write(op="set_labels", issue=42, labels=["ready-for-agent"]),
            write(op="comment", issue=42, body=f"{DISCLOSURE}\n\n..."),
            write(op="append_body", issue=43, body=f"{DISCLOSURE}\n\n..."),
            write(op="comment", issue=44, body=f"{DISCLOSURE}\n\nDuplicate of #41."),
            write(op="close", issue=44, reason="duplicate", duplicate_of=41),
            write(op="create_issue", title="Umbrella", body=DISCLOSURE, sub_issues=[41, 42]),
        ]
    }


def test_applier_accepts_a_valid_document():
    applier.validate(valid_document(), OPEN_ISSUES)


def test_applier_parse_rejects_malformed_json():
    with pytest.raises(applier.ValidationError):
        applier.parse_document("not json at all")
    with pytest.raises(applier.ValidationError):
        applier.parse_document('{"writes": [}')


@pytest.mark.parametrize(
    "broken",
    [
        {"writes": [write(op="delete", issue=42)]},
        {"writes": [write(op="set_labels", issue=99, labels=["bug"])]},
        {"writes": [write(op="set_labels", issue=42, labels=["evil"])]},
        {"writes": [write(op="set_labels", issue=42, labels=["bug", "enhancement"])]},
        {"writes": [write(op="set_labels", issue=42, labels=["needs-info", "ready-for-human"])]},
        {"writes": [write(op="set_labels", issue=42, labels=[])]},
        {"writes": [write(op="comment", issue=42, body="no disclosure")]},
        {"writes": [write(op="close", issue=44, reason="duplicate", duplicate_of=41)]},
        {"writes": [write(op="close", issue=41, reason="duplicate", duplicate_of=41)]},
        {
            "writes": [
                write(op="comment", issue=44, body=f"{DISCLOSURE}\n\nno number"),
                write(op="close", issue=44, reason="duplicate", duplicate_of=41),
            ]
        },
        {"writes": [write(op="create_issue", title="t", body=DISCLOSURE, sub_issues=[])]},
        {"writes": [write(op="create_issue", title="t", body=DISCLOSURE, sub_issues="41")]},
    ],
)
def test_applier_rejects_violations(broken):
    with pytest.raises(applier.ValidationError):
        applier.validate(broken, OPEN_ISSUES)


def test_applier_caps_created_umbrellas():
    documents = {
        "writes": [
            write(op="create_issue", title=f"u{index}", body=DISCLOSURE, sub_issues=[41])
            for index in range(applier.CAP + 1)
        ]
    }
    with pytest.raises(applier.ValidationError):
        applier.validate(documents, OPEN_ISSUES)


def test_applier_caps_touched_issues():
    open_issues = {number: number for number in range(1, 31)}
    document = {
        "writes": [write(op="set_labels", issue=number, labels=["bug"]) for number in range(1, applier.CAP + 2)]
    }
    with pytest.raises(applier.ValidationError):
        applier.validate(document, open_issues)


# --- vocabulary coupling -----------------------------------------------------


def test_applier_labels_match_the_skill_vocabulary():
    text = SKILL.read_text(encoding="utf-8")
    section = text.split("## Label vocabulary", 1)[1].split("## Outcomes", 1)[0]
    assert set(re.findall(r"`([a-z][a-z-]*)`", section)) == applier.LABELS
