---
name: Mnemorium CI

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  gatekeeper:
    runs-on: ubuntu-slim
    steps:
      - uses: amannn/action-semantic-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            feat
            fix
            refactor
            perf
            docs
            test
            build
            ci
            chore
            release
          scopes: |
            agent
            lint
            devenv
            test-e2e
            test-system
            sqlite3
            application
            development
            api

  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: devenv
      - name: Install devenv
        run: nix profile add nixpkgs#devenv
      - name: Build the devenv shell and run any git hooks
        run: devenv test
